export type Testimonial = {
  quote: string;
  name: string;
  location: string;
};

export const testimonials: Testimonial[] = [
  {
    quote: "For the past 5 years, we've followed the system of sports selections generated by the Scoregenix software. The win ratios and ROI potential have consistently exceeded expectations.",
    name: "Kip P.",
    location: "Toronto, Canada",
  },
  {
    quote: "It's a no-brainer for me. Stick to the picks and it's the best investment year in and year out. This isn't gambling — it's predictable and profitable.",
    name: "Scott S.",
    location: "Chicago, IL",
  },
  {
    quote: "The algorithm has proven to be a solid investment opportunity. I've been financially involved for less than a year, but I have full confidence in both the system and Troy's execution. The future is promising.",
    name: "Corey",
    location: "Ohio",
  },
  {
    quote: "I love that their selections are 100% numbers-driven, removing human emotion entirely. I'm very pleased with the results so far.",
    name: "Andrew M.",
    location: "Boston, MA",
  },
  {
    quote: "This is a sound and reliable product. The software delivers highly selective plays with strategic precision. I've seen strong success over the past 12 months.",
    name: "Nathen",
    location: "New York",
  },
  {
    quote: "This system removes the emotional pitfalls of sports gambling. Instead of betting on favorites or gut feelings, the software provides high-probability, data-driven plays. Even the secondary picks have been incredibly effective.",
    name: "Scott L.",
    location: "New York",
  },
];
